module.exports = {
    "Blackberry PlayBook": 'DeviceName.Blackberry_PlayBook',
    "BlackBerry Z30": 'DeviceName.BlackBerry_Z30',
    "Galaxy Note 3": 'DeviceName.Galaxy_Note_3',
    "Galaxy Note 2": 'DeviceName.Galaxy_Note_2',
    "Galaxy S3": 'DeviceName.Galaxy_S3',
    "Galaxy S5": 'DeviceName.Galaxy_S5',
    "Pixel 3": 'DeviceName.Pixel_3',
    "Pixel 3 XL": 'DeviceName.Pixel_3_XL',
    "Pixel 4": 'DeviceName.Pixel_4',
    "Pixel 4 XL": 'DeviceName.Pixel_4_XL',
    "iPad": 'DeviceName.iPad',
    "iPad 6th Gen": 'DeviceName.iPad_6th_Gen',
    "iPad 7th Gen": 'DeviceName.iPad_7th_Gen',
    "iPad Air 2": 'DeviceName.iPad_Air_2',
    "iPad Mini": 'DeviceName.iPad_Mini',
    "iPad Pro": 'DeviceName.iPad_Pro',
    "iPhone 11": 'DeviceName.iPhone_11',
    "iPhone 11 Pro": 'DeviceName.iPhone_11_Pro',
    "iPhone 11 Pro Max": 'DeviceName.iPhone_11_Pro_Max',
    "iPhone 4": 'DeviceName.iPhone_4',
    "iPhone 5/SE": 'DeviceName.iPhone_5SE',
    "iPhone 6/7/8": 'DeviceName.iPhone_6_7_8',
    "iPhone 6/7/8 Plus": 'DeviceName.iPhone_6_7_8_Plus',
    "iPhone X": 'DeviceName.iPhone_X',
    "iPhone XR": 'DeviceName.iPhone_XR',
    "iPhone XS": 'DeviceName.iPhone_XS',
    "iPhone XS Max": 'DeviceName.iPhone_XS_Max',
    "Kindle Fire HDX": 'DeviceName.Kindle_Fire_HDX',
    "Laptop with HiDPI screen": 'DeviceName.Laptop_with_HiDPI_screen',
    "Laptop with MDPI screen": 'DeviceName.Laptop_with_MDPI_screen',
    "Laptop with touch": 'DeviceName.Laptop_with_touch',
    "LG G6": 'DeviceName.LG_G6',
    "LG Optimus L70": 'DeviceName.LG_Optimus_L70',
    "Microsoft Lumia 550": 'DeviceName.Microsoft_Lumia_550',
    "Microsoft Lumia 950": 'DeviceName.Microsoft_Lumia_950',
    "Nexus 10": 'DeviceName.Nexus_10',
    "Nexus 4": 'DeviceName.Nexus_4',
    "Nexus 5": 'DeviceName.Nexus_5',
    "Nexus 5X": 'DeviceName.Nexus_5X',
    "Nexus 6": 'DeviceName.Nexus_6',
    "Nexus 6P": 'DeviceName.Nexus_6P',
    "Nexus 7": 'DeviceName.Nexus_7',
    "Nokia Lumia 520": 'DeviceName.Nokia_Lumia_520',
    "Nokia N9": 'DeviceName.Nokia_N9',
    "Pixel 2": 'DeviceName.Pixel_2',
    "Pixel 2 XL": 'DeviceName.Pixel_2_XL',
    "Galaxy A5": 'DeviceName.Galaxy_A5',
    "Galaxy Note 10": 'DeviceName.Galaxy_Note_10',
    "Galaxy Note 10 Plus": 'DeviceName.Galaxy_Note_10_Plus',
    "Galaxy Note 4": 'DeviceName.Galaxy_Note_4',
    "Galaxy Note 8": 'DeviceName.Galaxy_Note_8',
    "Galaxy Note 9": 'DeviceName.Galaxy_Note_9',
    "Galaxy S8": 'DeviceName.Galaxy_S8',
    "Galaxy S9": 'DeviceName.Galaxy_S9',
    "Galaxy S10": 'DeviceName.Galaxy_S10',
    "Galaxy S8 Plus": 'DeviceName.Galaxy_S8_Plus',
    "Galaxy S9 Plus": 'DeviceName.Galaxy_S9_Plus',
    "Galaxy S10 Plus": 'DeviceName.Galaxy_S10_Plus',
    "OnePlus 7T": 'DeviceName.OnePlus_7T',
    "OnePlus 7T Pro": 'DeviceName.OnePlus_7T_Pro',
}