CHECK_SETTING = "Check Settings keyword"
UFG_RELATED = "UFG only"
TARGET_SUPPORT = "Allow to pass Target keyword"
CHECK_SETTINGS_SUPPORT = "Allow to pass Check Settings keywords"
CHECK_FLOW = "Check flow"
